"""add description column

Revision ID: 20b4f2c65707
Revises: c7ab17765590
Create Date: 2026-05-26 04:51:21.314013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20b4f2c65707'
down_revision: Union[str, Sequence[str], None] = 'c7ab17765590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_details', sa.Column('description', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_details', 'description')
    # ### end Alembic commands ###
